-- Description: This file contains the SQL commands to insert data into the tables of the database.
-- Data entries were generated by Ghat GPT and modified to suit the queries.

-- Users table
INSERT INTO Users (Username, Email, PasswordHash, Birthdate, Gender, HeightCM) VALUES
('user1', 'user1@example.com', 'hashed_password', '1990-01-01', 'Male', 175),
('user2', 'user2@example.com', 'hashed_password', '1985-05-12', 'Female', 165),
('user3', 'user3@example.com', 'hashed_password', '1992-07-23', 'Male', 180),
('user4', 'user4@example.com', 'hashed_password', '1988-03-15', 'Female', 160),
('user5', 'user5@example.com', 'hashed_password', '1995-10-08', 'Other', 170);


-- Workouts table
INSERT INTO Workouts (UserID, Type, DurationMinutes, DistanceKM, CaloriesBurned, WorkoutDate) VALUES
(1, 'Cycling', 90, 2, 200, '2024-03-10'),
(2, 'Yoga', 45, 0, 400, '2024-03-10'),
(1, 'Weightlifting', 90, 0, 600, '2024-03-11'),
(2, 'Running', 60, 0, 600, '2024-02-27'),
(2, 'Weightlifting', 120, 0, 600, '2024-02-21'),
(2, 'Weightlifting', 120, 0, 600, '2024-02-27'),
(3, 'Cycling', 60, 15, 400, '2024-02-17'),
(4, 'Swimming', 30, 15, 600, '2024-02-10'),
(5, 'Cycling', 90, 0, 400, '2024-02-06'),
(4, 'Swimming', 60, 15, 400, '2024-02-05'),
(2, 'Yoga', 30, 0, 200, '2024-02-20'),
(3, 'Weightlifting', 60, 0, 500, '2024-02-21'),
(3, 'Yoga', 30, 0, 300, '2024-02-16'),
(3, 'Running', 120, 0, 500, '2024-02-03'),
(2, 'Cycling', 45, 15, 600, '2024-02-23');


-- Nutrition table
INSERT INTO Nutrition (UserID, MealType, FoodItem, Calories, CarbsG, ProteinsG, FatsG, NutritionDate) VALUES
(4, 'Lunch', 'Sandwich', 200, 20, 15, 5, '2024-02-24'),
(4, 'Lunch', 'Fruit', 500, 50, 30, 20, '2024-02-22'),
(5, 'Breakfast', 'Salad', 500, 50, 30, 10, '2024-03-03'),
(2, 'Breakfast', 'Steak', 300, 20, 30, 10, '2024-02-28'),
(4, 'Breakfast', 'Salad', 400, 50, 30, 10, '2024-03-11'),
(4, 'Breakfast', 'Salad', 700, 30, 15, 10, '2024-02-23'),
(1, 'Breakfast', 'Steak', 200, 60, 20, 10, '2024-03-04'),
(3, 'Breakfast', 'Fruit', 400, 30, 10, 20, '2024-02-12'),
(4, 'Dinner', 'Oatmeal', 300, 20, 20, 10, '2024-02-27'),
(5, 'Dinner', 'Steak', 700, 30, 30, 20, '2024-02-15'),
(2, 'Snack', 'Fruit', 200, 60, 5, 5, '2024-02-19'),
(1, 'Lunch', 'Salad', 500, 40, 25, 15, '2024-02-25'),
(3, 'Dinner', 'Sandwich', 400, 40, 20, 10, '2024-02-17'),
(5, 'Snack', 'Oatmeal', 300, 60, 5, 15, '2024-03-14'),
(2, 'Breakfast', 'Oatmeal', 300, 60, 5, 15, '2024-03-14'),
(3, 'Lunch', 'Steak', 700, 0, 50, 30, '2024-02-21'),
(1, 'Dinner', 'Fruit', 200, 50, 2, 1, '2024-03-12'),
(4, 'Snack', 'Sandwich', 300, 30, 20, 10, '2024-02-29'),
(2, 'Lunch', 'Salad', 400, 20, 15, 5, '2024-03-03'),
(5, 'Breakfast', 'Oatmeal', 300, 60, 5, 15, '2024-02-06');

-- HealthMetrics table
INSERT INTO HealthMetrics (UserID, RecordDate, HeartRate, BloodPressure, WeightKG, BodyFatPercentage) VALUES
(1, '2024-02-15', 83, '120/87', 70, 12.44),
(2, '2024-03-01', 65, '111/84', 60, 23.88),
(3, '2024-03-07', 92, '125/73', 80, 23.41),
(4, '2024-02-19', 92, '131/72', 55, 11.63),
(5, '2024-02-15', 64, '118/82', 65, 18.28),
(1, '2024-02-20', 65, '134/82', 70, 15.13),
(2, '2024-02-20', 62, '140/87', 60, 19.49),
(3, '2024-02-19', 69, '121/88', 80, 23.61),
(4, '2024-02-23', 80, '140/90', 55, 16.04),
(5, '2024-03-12', 72, '139/90', 65, 21.83);

-- Sleep table
INSERT INTO Sleep (UserID, StartDateTime, EndDateTime, Quality) VALUES
(5, '2024-02-21 23:18:00', '2024-02-22 06:18:00', 'Good'),
(5, '2024-02-23 22:24:00', '2024-02-24 07:24:00', 'Average'),
(5, '2024-02-25 22:51:00', '2024-02-26 07:51:00', 'Good'),
(5, '2024-03-02 22:27:00', '2024-03-03 05:27:00', 'Average'),
(5, '2024-03-06 22:12:00', '2024-03-07 04:12:00', 'Average'),
(2, '2024-02-25 23:21:00', '2024-02-26 07:21:00', 'Average'),
(2, '2024-02-19 23:53:00', '2024-02-20 08:53:00', 'Average'),
(3, '2024-03-07 23:29:00', '2024-03-08 08:29:00', 'Average'),
(3, '2024-02-18 22:44:00', '2024-02-19 06:44:00', 'Average'),
(4, '2024-02-21 22:35:00', '2024-02-22 07:35:00', 'Good'),
(1, '2024-02-27 22:57:00', '2024-02-28 05:57:00', 'Poor');

